version: '3'
services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: finperson
      MYSQL_USER: rafael
      MYSQL_PASSWORD: secret
    ports:
        - '3306:3306'
    volumes:
        - ./data:/var/lib/mysql
